CREATE TABLE IF NOT EXISTS `Products` (
  `Id` INT AUTO_INCREMENT,
  `Name` NVARCHAR(100) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Stock` INT NOT NULL,
  `Obsolete` BIT NOT NULL DEFAULT 0,
  `ModTime` DATETIME NOT NULL,
  PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
